# Makefile for the Dirty code
#
# * March 2008 Karl Misselt <misselt@as.arizona.edu> 
# - First import - don't know if it works for dirty 
#   code yet....

RM = /bin/rm -f
CPP = g++

INCDIR = include
#UINCDIR = lib/include
LIBS = -lcfitsio

PROGRAM = dirty

SOURCES = $(wildcard code/*.cpp)
SOURCES += $(wildcard lib/*.cpp)

OBJECTS = ${SOURCES:.cpp=.o}
#CPPFLAGS = -I${INCDIR} -I${UINCDIR} -O3 
CPPFLAGS = -I${INCDIR} -O3 

BUILDOBJ = $(CPP) $(CPPFLAGS)
BUILDLNK = $(CPP) $(LDFLAGS)

all:  ${PROGRAM}

$(PROGRAM) : $(OBJECTS)
	$(BUILDLNK) $^ $(LIBS) -o $(@)

-include $(SOURCES:.cpp=.d)

%.d: %.cpp
	@set -e; rm -f $@; \
	$(CPP) -MM $(CPPFLAGS) $(LDFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$

clean:
	$(RM) $(OBJECTS)
	$(RM) dirty

.cpp.o : 
	$(BUILDOBJ) -c $< -o $@
